### ISSUE TITLE
Chat functionality not work proper

### ISSUE THREAD

**Issue by ghost** [DamiFlutter/Dating-App#2]

**Comment by DamilolaDami** [comment]
Message me on gmail

**Comment by BhautikVaghasiya** [comment]
HI sir,
Good evening,
Dating app with firebase  super codeing understand.... All functionally..
Good coding skill,,,
But show one issue message send function blank...

**Comment by DamiFlutter** [comment]
Hello I will build this project for you completely
Message me if you are interested

**Comment by yerdna1983** [comment]
Yes, some issues here

**Comment by DamilolaDami** [comment]
What issues?

**Comment by Amresh8586** [comment]
issue is chat functionality is not working

**Comment by DamilolaDami** [comment]
What issues are you having
