### ISSUE TITLE
"FirebaseOptions cannot be null when creating the default app."

### ISSUE THREAD

**Issue by gambit767** [DamiFlutter/Dating-App#3]
Hey can you please share how to fix firebase_core_web.dart ?

It is showing "FirebaseOptions cannot be null when creating the default app." 

I tried updated the below fields to my Firebase values but it still doesn't work:

apiKey: 
databaseURL: 
projectId: 
storageBucket: 
messagingSenderId: 
appId:

Your help would be much appreciated.

**Comment by DamilolaDami** [comment]
Add it to the initialization of firebase sdk in your main function
